CREATE DATABASE QLDA;
GO
USE QLDA;
GO

CREATE TABLE DUAN (
    Mada NVARCHAR(50) PRIMARY KEY,
    Tenda NVARCHAR(100),
    Congviecda NVARCHAR(100),
    Songayda INT
);

CREATE TABLE NHANVIEN (
    Manv NVARCHAR(50) PRIMARY KEY,
    Hoten NVARCHAR(100),
    SoCMTND NVARCHAR(50),
    Ngaysinh DATE,
    Gioitinh NVARCHAR(10),
    Diachi NVARCHAR(100)
);

CREATE TABLE CHUYENMON (
    Manv NVARCHAR(50) FOREIGN KEY REFERENCES NHANVIEN(Manv),
    Chuyenmon NVARCHAR(100),
    PRIMARY KEY (Manv)
);

CREATE TABLE TRINHDO (
    Manv NVARCHAR(50) FOREIGN KEY REFERENCES NHANVIEN(Manv),
    Trinhdo NVARCHAR(100),
    PRIMARY KEY (Manv)
);

CREATE TABLE NHANVIEN_DUAN (
    Manv NVARCHAR(50) FOREIGN KEY REFERENCES NHANVIEN(Manv),
    Mada NVARCHAR(50) FOREIGN KEY REFERENCES DUAN(Mada),
    Ngaybd DATE,
    Ngaykt DATE,
    PRIMARY KEY (Manv, Mada)
);

-- Insert sample data
INSERT INTO DUAN VALUES ('DA1', N'Dự án 1', N'Công việc 1', 30);
INSERT INTO DUAN VALUES ('DA2', N'Dự án 2', N'Công việc 2', 60);
INSERT INTO DUAN VALUES ('DA3', N'Dự án 3', N'Công việc 3', 90);

INSERT INTO NHANVIEN VALUES ('NV1', N'Nhân viên 1', '123456789', '1990-01-01', N'Nam', N'Hà Nội');
INSERT INTO NHANVIEN VALUES ('NV2', N'Nhân viên 2', '987654321', '1995-02-02', N'Nữ', N'HCM');
INSERT INTO NHANVIEN VALUES ('NV3', N'Nhân viên 3', '111222333', '1985-03-03', N'Nam', N'Đà Nẵng');

INSERT INTO CHUYENMON VALUES ('NV1', N'CNTT');
INSERT INTO CHUYENMON VALUES ('NV2', N'Kế toán');
INSERT INTO CHUYENMON VALUES ('NV3', N'Kỹ thuật');

INSERT INTO TRINHDO VALUES ('NV1', N'Đại học');
INSERT INTO TRINHDO VALUES ('NV2', N'Cao đẳng');
INSERT INTO TRINHDO VALUES ('NV3', N'Thạc sĩ');

INSERT INTO NHANVIEN_DUAN VALUES ('NV1', 'DA1', '2023-01-01', '2023-01-30');
INSERT INTO NHANVIEN_DUAN VALUES ('NV2', 'DA2', '2023-02-01', '2023-03-30');
INSERT INTO NHANVIEN_DUAN VALUES ('NV3', 'DA3', '2023-03-01', '2023-05-30');
