CREATE DATABASE QLKD;
GO
USE QLKD;
GO

CREATE TABLE NCC (
    Mancc NVARCHAR(50) PRIMARY KEY,
    Tenncc NVARCHAR(100),
    DiachiNCC NVARCHAR(100)
);

CREATE TABLE HDMUA (
    SoHD NVARCHAR(50) PRIMARY KEY,
    Ngaymua DATE,
    Mancc NVARCHAR(50) FOREIGN KEY REFERENCES NCC(Mancc)
);

CREATE TABLE HANG (
    Mahang NVARCHAR(50) PRIMARY KEY,
    Tenhang NVARCHAR(100),
    DVT NVARCHAR(50)
);

CREATE TABLE CHITIETMUA (
    SoHD NVARCHAR(50) FOREIGN KEY REFERENCES HDMUA(SoHD),
    Mahang NVARCHAR(50) FOREIGN KEY REFERENCES HANG(Mahang),
    Soluongmua INT,
    Dongiamua FLOAT,
    PRIMARY KEY (SoHD, Mahang)
);

CREATE TABLE KHACH (
    Makh NVARCHAR(50) PRIMARY KEY,
    Tenkh NVARCHAR(100),
    Diachikh NVARCHAR(100)
);

CREATE TABLE HDBAN (
    SoHDB NVARCHAR(50) PRIMARY KEY,
    Ngayban DATE,
    Makh NVARCHAR(50) FOREIGN KEY REFERENCES KHACH(Makh)
);

CREATE TABLE CHITIETBAN (
    SoHDB NVARCHAR(50) FOREIGN KEY REFERENCES HDBAN(SoHDB),
    Mahang NVARCHAR(50) FOREIGN KEY REFERENCES HANG(Mahang),
    Soluongban INT,
    Dongiaban FLOAT,
    PRIMARY KEY (SoHDB, Mahang)
);

-- Insert sample data
INSERT INTO NCC VALUES ('NCC1', N'Nhà cung cấp 1', N'Hà Nội');
INSERT INTO NCC VALUES ('NCC2', N'Nhà cung cấp 2', N'HCM');
INSERT INTO NCC VALUES ('NCC3', N'Nhà cung cấp 3', N'Đà Nẵng');

INSERT INTO HDMUA VALUES ('HDM1', '2023-01-01', 'NCC1');
INSERT INTO HDMUA VALUES ('HDM2', '2023-01-02', 'NCC2');
INSERT INTO HDMUA VALUES ('HDM3', '2023-01-03', 'NCC3');

INSERT INTO HANG VALUES ('H1', N'Hàng 1', N'Cái');
INSERT INTO HANG VALUES ('H2', N'Hàng 2', N'Chiếc');
INSERT INTO HANG VALUES ('H3', N'Hàng 3', N'Hộp');

INSERT INTO CHITIETMUA VALUES ('HDM1', 'H1', 10, 10000);
INSERT INTO CHITIETMUA VALUES ('HDM2', 'H2', 20, 20000);
INSERT INTO CHITIETMUA VALUES ('HDM3', 'H3', 30, 30000);

INSERT INTO KHACH VALUES ('KH1', N'Khách 1', N'Hà Nội');
INSERT INTO KHACH VALUES ('KH2', N'Khách 2', N'HCM');
INSERT INTO KHACH VALUES ('KH3', N'Khách 3', N'Đà Nẵng');

INSERT INTO HDBAN VALUES ('HDB1', '2023-02-01', 'KH1');
INSERT INTO HDBAN VALUES ('HDB2', '2023-02-02', 'KH2');
INSERT INTO HDBAN VALUES ('HDB3', '2023-02-03', 'KH3');

INSERT INTO CHITIETBAN VALUES ('HDB1', 'H1', 5, 12000);
INSERT INTO CHITIETBAN VALUES ('HDB2', 'H2', 10, 25000);
INSERT INTO CHITIETBAN VALUES ('HDB3', 'H3', 15, 35000);
